---
layout: post
title: "AWS-CLI利用に伴うエラー"
date: 2016-01-08 00:47:54
categories: aws
---
<p>社内プロキシ内からAWSを利用しようとした際に下記エラーが出て困っております。<br>
ネットを調べたところ環境変数にプロキシを設定すれば大丈夫とのことですが、<br>
それでは解決されなかったため質問しております。</p>

<p>解決策をご教示願えませんでしょうか。</p>

<p>&lt;環境></p>

<p>windows 7</p>

<p>&lt;実行文></p>

<pre><code>aws ec2 describe-instances --debug
</code></pre>

<p>&lt;エラー本文:下記が繰り返し表示された末リトライエラーとなっています></p>

<pre><code>POST
/

host:ec2.us-west-2a.amazonaws.com
user-agent:aws-cli/1.9.17 Python/2.7.9 Windows/7 botocore/1.3.17
x-amz-date:20160108T003725Z

host;user-agent;x-amz-date
7371039207d67c4be2f6abbb39dcd980a6861eef125be9b5437a5f5308278f8c
2016-01-08 09:37:25,283 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20160108T003725Z
20160108/us-west-2a/ec2/aws4_request
82e1204a2de86f6481bf609fe69424a730c4fd2c8573527b28461fe2813d8040
2016-01-08 09:37:25,283 - MainThread - botocore.auth - DEBUG - Signature:
494dd8db25feb91126950d6131648778d09e9973311cc4a0801f38e588cb69dd
2016-01-08 09:37:25,283 - MainThread - botocore.endpoint - DEBUG - Sending http
request: &lt;PreparedRequest [POST]&gt;
2016-01-08 09:37:25,283 - MainThread - botocore.vendored.requests.packages.urlli
b3.connectionpool - INFO - Starting new HTTPS connection (5): ec2.us-west-2a.ama
zonaws.com
2016-01-08 09:37:25,503 - MainThread - botocore.endpoint - DEBUG - ConnectionErr
or received when sending HTTP request.
Traceback (most recent call last):
 File "botocore\endpoint.pyc", line 168, in _get_response
 File "botocore\vendored\requests\sessions.pyc", line 573, in send
 File "botocore\vendored\requests\adapters.pyc", line 424, in send
ConnectionError: HTTPSConnectionPool(host='ec2.us-west-2a.amazonaws.com', port=4
43): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to p
roxy.', error('Tunnel connection failed: 503 Service Unavailable',)))
2016-01-08 09:37:25,503 - MainThread - botocore.hooks - DEBUG - Event needs-retr
y.ec2.DescribeInstances: calling handler &lt;botocore.retryhandler.RetryHandler obj
ect at 0x0321C570&gt;
2016-01-08 09:37:25,503 - MainThread - awscli.clidriver - DEBUG - Exception caug
ht in main()
Traceback (most recent call last):
 File "awscli\clidriver.pyc", line 186, in main
 File "awscli\clidriver.pyc", line 377, in __call__
 File "awscli\clidriver.pyc", line 546, in __call__
 File "awscli\clidriver.pyc", line 671, in invoke
 File "awscli\clidriver.pyc", line 680, in _display_response
 File "awscli\formatter.pyc", line 68, in __call__
 File "botocore\paginate.pyc", line 271, in build_full_result
 File "botocore\paginate.pyc", line 85, in __iter__
 File "botocore\paginate.pyc", line 157, in _make_request
 File "botocore\client.pyc", line 310, in _api_call
 File "botocore\client.pyc", line 396, in _make_api_call
 File "botocore\endpoint.pyc", line 111, in make_request
 File "botocore\endpoint.pyc", line 140, in _send_request
 File "botocore\endpoint.pyc", line 213, in _needs_retry
 File "botocore\hooks.pyc", line 226, in emit
 File "botocore\hooks.pyc", line 209, in _emit
 File "botocore\retryhandler.pyc", line 183, in __call__
 File "botocore\retryhandler.pyc", line 250, in __call__
 File "botocore\retryhandler.pyc", line 273, in _should_retry
 File "botocore\retryhandler.pyc", line 313, in __call__
 File "botocore\retryhandler.pyc", line 222, in __call__
 File "botocore\retryhandler.pyc", line 355, in _check_caught_exception
ConnectionError: HTTPSConnectionPool(host='ec2.us-west-2a.amazonaws.com', port=4
43): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to p
roxy.', error('Tunnel connection failed: 503 Service Unavailable',)))
2016-01-08 09:37:25,503 - MainThread - awscli.clidriver - DEBUG - Exiting with r
c 255

HTTPSConnectionPool(host='ec2.us-west-2a.amazonaws.com', port=443): Max retries
exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', error('Tu
nnel connection failed: 503 Service Unavailable',)))
</code></pre>

<p>事前にプロキシの設定はしています。</p>

<pre><code>set HTTP_PROXY=http://proxy.xxxxxx.co.jp:8080
set HTTPS_PROXY=http://proxy.xxxxxx.co.jp:8080
</code></pre>

<p>よろしくお願い致します。</p>
