---
layout: post
title: Laravel5における認証時エラー
date: 2016-11-15 00:51:55
categories: php laravel
---
<!-- {% raw %} -->
<p>Laravelのエラーについて質問があります。</p>

<p>会社を辞められた方から引き継いだプロジェクトがあり、そのプロジェクトを確認していたところ、認証処理のところでlaravelのログに以下のようなエラーが出力されていました。<br>
それも認証処理で必ずエラーが出力されています。</p>

<pre><code>[2016-11-15 09:25:06] local.ERROR: #0 C:\xampp\htdocs\hogehoge\vendor\laravel\framework\src\Illuminate\Routing\Router.php(750): Illuminate\Routing\RouteCollection-&gt;match(Object(Illuminate\Http\Request))
#1 C:\xampp\htdocs\hogehoge\vendor\laravel\framework\src\Illuminate\Routing\Router.php(659): Illuminate\Routing\Router-&gt;findRoute(Object(Illuminate\Http\Request))
#2 C:\xampp\htdocs\hogehoge\vendor\laravel\framework\src\Illuminate\Routing\Router.php(635): Illuminate\Routing\Router-&gt;dispatchToRoute(Object(Illuminate\Http\Request))
#3 C:\xampp\htdocs\hogehoge\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(236): Illuminate\Routing\Router-&gt;dispatch(Object(Illuminate\Http\Request))
#4 [internal function]: Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#5 C:\xampp\htdocs\hogehoge\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#6 C:\xampp\htdocs\hogehoge\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#7 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#8 C:\xampp\htdocs\hogehoge\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#9 C:\xampp\htdocs\hogehoge\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#11 C:\xampp\htdocs\hogehoge\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#12 C:\xampp\htdocs\hogehoge\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(62): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 [internal function]: Illuminate\Session\Middleware\StartSession-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#14 C:\xampp\htdocs\hogehoge\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#15 C:\xampp\htdocs\hogehoge\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#17 C:\xampp\htdocs\hogehoge\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#18 C:\xampp\htdocs\hogehoge\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#20 C:\xampp\htdocs\hogehoge\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#21 C:\xampp\htdocs\hogehoge\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#23 C:\xampp\htdocs\hogehoge\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#24 [internal function]: Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 C:\xampp\htdocs\hogehoge\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#26 C:\xampp\htdocs\hogehoge\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(122): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#27 C:\xampp\htdocs\hogehoge\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(87): Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter(Object(Illuminate\Http\Request))
#28 C:\xampp\htdocs\hogehoge\index.php(54): Illuminate\Foundation\Http\Kernel-&gt;handle(Object(Illuminate\Http\Request))
#29 {main}  
</code></pre>

<p>そして、不思議なのは、このエラーが吐かれているにも関わらず、処理が継続され、認証も正常に実施されているのです。<br>
その辞めれられた方にも問い合わせたのですが「コード見れないのでわからない」と言う事でした・・・。<br>
ちなみに、上記エラーでGoogle検索してみたところ、同じようなエラーの凡例がいくつか見つけられたのですが、なかなか理解できずにいます。<br>
ちなみに、「routes.phpでGETとPOSTを間違っているのでは？」という事例が記載されているサイトがありましたが、認証用ページではGETとPOSTの両方を行っています。<br>
また、php artisanコマンドでキャッシュのクリアも試してみましたが結果は変わらずです。</p>

<p>このエラーはどのような場合に発生するのでしょうか。<br>
またエラーを解消するためにはどのような対策を採ればよいでしょうか。<br>
ザックリした内容で申し訳ありませんが、ご教示願います。</p>
<!-- {% endraw %} -->
