---
layout: post
title: AnacondaのパッケージMatplotlibをPython IDLEで使用したい。
date: 2017-08-28 08:58:44
categories: python3 anaconda matplotlib
---
<p>Python IDLEでMatplotlibパッケージを使用したいのですが、Anacondaをインストールした後に、IDLEでMatplotlibをインポートしても以下のようなエラーが発生(numpyはインポート成功したのですが）してしまいます。ちなみにTerminalではきちんと機能します。</p>

<pre><code>&gt;&gt;&gt; import matplotlib.pyplot as plt
Traceback (most recent call last):
  File "&lt;pyshell#2&gt;", line 1, in &lt;module&gt;
import matplotlib.pyplot as plt
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/matplotlib/pyplot.py", line 29, in &lt;module&gt;
import matplotlib.colorbar
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/matplotlib/colorbar.py", line 36, in &lt;module&gt;
import matplotlib.contour as contour
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/matplotlib/contour.py", line 23, in &lt;module&gt;
import matplotlib.text as text
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/matplotlib/text.py", line 33, in &lt;module&gt;
from matplotlib.backend_bases import RendererBase
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 66, in &lt;module&gt;
import matplotlib.backend_tools as tools
  File "&lt;frozen importlib._bootstrap&gt;", line 961, in _find_and_load
  File "&lt;frozen importlib._bootstrap&gt;", line 950, in _find_and_load_unlocked
  File "&lt;frozen importlib._bootstrap&gt;", line 655, in _load_unlocked
  File "&lt;frozen importlib._bootstrap_external&gt;", line 674, in exec_module
  File "&lt;frozen importlib._bootstrap_external&gt;", line 779, in get_code
  File "&lt;frozen importlib._bootstrap_external&gt;", line 487, in _compile_bytecode
ValueError: bad marshal data (unknown type code)
</code></pre>
