---
layout: post
title: os.walk()、shutilcopy()でエラーが発生する
date: 2017-11-15 06:47:26
categories: python
---
```
#! python3
#デスクトップにある特定のファイルをコピーしてフォルダに移動する

import shutil, os
os.chdir('C:\\Users\\sugimoto\\Desktop\\atom作業フォルダ')
for foldername, subfolders, filenames in os.walk('.'):
    for filename in filenames:
        if filename.endswith('.txt') or filename.endswith('.png') or filename.endswith('.py'):
            shutil.copy(filename, '..\\foo')
        else:
            print('該当するファイルが見つかりませんでした。')
```

<p>このコードは.txtファイルと.pngファイルだけをshutil.copy()でコピーするコードです。<br>
しかしこれを実行すると、No such file or directory: 'third-party.txt'（そんなファイルはありません。）というエラーがでてしまいます。</p>

<p>しかしながら</p>

```
import os
os.chdir('C:\\Users\\sugimoto\\Desktop\\atom作業フォルダ')
folder = os.getcwd()
for foldername, subfolders, filenames in os.walk(folder):
    for filename in  filenames:    
        print('ファイル: ' + filename)
```

<p>↑のコードを実行すると確かに大量のファイルが表示されるのです。ファイルは存在するのに、ファイルが存在しないというエラーがでてしまいます。これは何が原因なのでしょうか？</p>
