---
layout: post
title: pythonの配列にdatetime型のデータを入力したい
date: 2017-07-04 04:56:11
categories: python
---
<p>質問が不明瞭なままで申し訳ありませんでした</p>

<p>pythonの配列にpsqlに格納したdatetime型のデータを入力しようとすると、最初の一つ目は入るにもかかわらず、二つ目以降は型が違うと言われて入らなくなってしまいます</p>

<p>以下ソースです。</p>

<pre><code># -*-coding:utf-8-*- 
# -*-coding:unicode-*- 
import csv 
import binascii 
import string 
import psycopg2 
import datetime 
from datetime import datetime as dt 

connection = psycopg2.connect("(省略)") 
connection.get_backend_pid() 

cur = connection.cursor() 
# SQLコマンド実行 (今回はテーブル作成) 
try: 
    cur.execute("CREATE TABLE table(id serial,date date,time time,idm text,deviceid);") 
    print'ファイルを作成しました' 
except Exception as IOError: 
    print'ファイルが見つかりました' 
connection.commit() 

i = 0 
cur.execute("select*from table") 
#日付の記入 
now = 0 
count =0 
for row in cur: 
if not now==row[1]: 
print now,row[1],count 
date = (row[1]) #配列の作成
for l in range(count): 
    try: 
        print row[1],date[l],l  
    except Exception as e: 
        break 
    if now!=0 and row[1] == date[l]: 
        break 
    count = count +1 
    count_max =count 
    date = date + row[1]　#配列への追加(ここでエラーが出る)  
    now = row[1] 
    active[row[3],row[1]]=1 
</code></pre>

<p>エラーメッセージ：</p>

<pre><code>Traceback (most recent call last): 
File "actable.py", line 43, in &lt;module&gt; 
date = date + row[1] 
TypeError: unsupported operand type(s) for +: 'datetime.date' and　'datetime.date' 
</code></pre>

<p>型が違うと言われても同じ型のはずなので解決策が全く分かりません</p>
