---
layout: post
title: webスクレイピング実行時のエラー
date: 2018-04-21 15:33:27
categories: python web-scraping
---
<p>下記サイトを参考にwebスクレイピングをはじめて試しています。<br>
<a href="http://blog.aidemy.net/entry/2017/12/17/214715" rel="nofollow noreferrer">http://blog.aidemy.net/entry/2017/12/17/214715</a></p>

<p>物は試しとAPI_KEYとCUSTOM_SEARCH_ENGINEだけ取得し、画像収集のソースコードをそのまま使用させていただき実行すると下記のエラーが発生しました。</p>

<pre><code>Traceback (most recent call last):
  File "gazou_shutoku.py", line 52, in &lt;module&gt;
    img_list = get_image_url(keywords[j],100)
  File "gazou_shutoku.py", line 26, in get_image_url
    res = urllib.request.urlopen(query_img)
  File "C:\Users\ユーザー名\Anaconda3\envs\gazou_atsume\lib\urllib\request.
py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\ユーザー名\Anaconda3\envs\gazou_atsume\lib\urllib\request.
py", line 532, in open
    response = meth(req, response)
  File "C:\Users\ユーザー名\Anaconda3\envs\gazou_atsume\lib\urllib\request.
py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\ユーザー名\Anaconda3\envs\gazou_atsume\lib\urllib\request.
py", line 570, in error
    return self._call_chain(*args)
  File "C:\Users\ユーザー名\Anaconda3\envs\gazou_atsume\lib\urllib\request.
py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\ユーザー名\Anaconda3\envs\gazou_atsume\lib\urllib\request.
py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
</code></pre>

<p>何が問題なのでしょうか？よろしくお願いします。</p>
