---
layout: post
title: PHPのPDOStatement::executeが失敗したとき、Falseを返すのかExceptionを投げるのか
date: 2018-02-08 09:25:59
categories: php pdo
---
<!-- {% raw %} -->
<p><code>PDO::ERRMODE_EXCEPTION</code>のとき、</p>

<pre><code>try {
    $stmt = $pdo-&gt;prepare("SELECT * FROM po");
    $result= $stmt-&gt;execute();
    if (!$result) {
        throw new Exception ("execute_false");
    }
} catch (Exception $e) {
    var_dump($e-&gt;getMessage());
}
</code></pre>

<p>とすると、<br>
<code>Base table or view not found: 1146 Table 'hoge_table.po' doesn't exist</code><br>
となり、<code>execute()</code>が<code>false</code>ではなく例外を投げているような気がします。</p>

<p>しかし、<a href="http://php.net/manual/ja/pdostatement.execute.php" rel="nofollow noreferrer">ドキュメント</a>を見ても、executeが例外を出すという記述はありません。たとえば<a href="http://php.net/manual/ja/pdo.prepare.php" rel="nofollow noreferrer">prepare</a>のところには例外を吐くと書かれています。</p>

<p>これについて、<code>execute</code>が例外を出したのではなく、<code>prepare</code>の例外が<br>
<code>execute</code>の実行により起こり、<code>execute</code>が例外を出したように見える、という解釈で正しいのでしょうか？</p>

<p>また、<code>execute</code>自身が<code>false</code>を返す失敗とはどのようなものなのでしょうか。</p>

<p>よろしくお願いします。</p>
<!-- {% endraw %} -->
