---
layout: post
title: OpenPoseをGPUで動かそうとすると No module name 'cupy'
date: 2018-04-19 12:27:34
categories: python 深層学習 chainer
---
<!-- {% raw %} -->
<p>下記サイトを参考にopen poseを試しています。<br>
<a href="https://github.com/DeNA/Chainer_Realtime_Multi-Person_Pose_Estimation/blob/master/README_JP.md" rel="nofollow noreferrer">https://github.com/DeNA/Chainer_Realtime_Multi-Person_Pose_Estimation/blob/master/README_JP.md</a><br>
CPUでは問題なく動作したのですがあまりに動作が遅いためGPUで動作できるように試みてみましたが下記エラーが発生しました。よろしくお願いします。</p>

<p>windows7<br>
chainer 4.0.0<br>
anaconda 1.8.3<br>
cuda インストール済<br>
cuDNN インストール済</p>

<p>下記がエラーメッセージです。</p>

<pre><code>(OpenPose) C:\Users\ユーザー名\Documents\open_pose\Chainer_Realtime_Multi-P
erson_Pose_Estimation&gt;python pose_detector.py posenet models/coco_posenet.npz --
img data/person.png --gpu 0
Loading the model...
Traceback (most recent call last):
  File "pose_detector.py", line 568, in &lt;module&gt;
    pose_detector = PoseDetector(args.arch, args.weights, device=args.gpu, preci
se=args.precise)
  File "pose_detector.py", line 30, in __init__
    cuda.get_device_from_id(device).use()
  File "C:\Users\ユーザー名\Anaconda3\envs\OpenPose\lib\site-packages\chain
er\backends\cuda.py", line 160, in get_device_from_id
    check_cuda_available()
  File "C:\Users\ユーザー名\Anaconda3\envs\OpenPose\lib\site-packages\chain
er\backends\cuda.py", line 90, in check_cuda_available
    raise RuntimeError(msg)
RuntimeError: CUDA environment is not correctly set up
(see https://github.com/chainer/chainer#installation).No module named 'cupy'

(OpenPose) C:\Users\ユーザー名\Documents\open_pose\Chainer_Realtime_Multi-P
erson_Pose_Estimation&gt;pip install cupy
Collecting cupy
  Using cached https://files.pythonhosted.org/packages/38/14/ddb1a13f77a50d72181
4e28181ae90e0d57c3f8d4faa9a7b2e028cfcc99a/cupy-4.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    **************************************************
    *** WARNING: Cannot find nvToolsExt. nvtx was disabled.
    **************************************************
    Options: {'package_name': 'cupy', 'long_description': None, 'wheel_libs': []
, 'no_rpath': False, 'profile': False, 'linetrace': False, 'annotate': False, 'n
o_cuda': False}

    -------- Configuring Module: cuda --------
    Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Bui
ld Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    ************************************************************
    * CuPy Configuration Summary                               *
    ************************************************************

    Build Environment:
      Include directories: ['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CU
DA\\v9.1\\include', 'C:\\Program Files\\NVIDIA Corporation\\NvToolsExt\\include'
]
      Library directories: ['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CU
DA\\v9.1\\bin', 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.1\\li
b\\x64', 'C:\\Program Files\\NVIDIA Corporation\\NvToolsExt\\lib\\x64']
      nvcc command       : ['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CU
DA\\v9.1\\bin/nvcc.exe']

    Environment Variables:
      CFLAGS          : (none)
      LDFLAGS         : (none)
      LIBRARY_PATH    : (none)
      CUDA_PATH       : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1
      NVCC            : (none)

    Modules:
      cuda      : No
        -&gt; Include files not found: ['cublas_v2.h', 'cuda.h', 'cuda_profiler_api
.h', 'cuda_runtime.h', 'cufft.h', 'curand.h', 'cusparse.h', 'nvrtc.h']
        -&gt; Check your CFLAGS environment variable.

    ERROR: CUDA could not be found on your system.
    Please refer to the Installation Guide for details:
    https://docs-cupy.chainer.org/en/stable/install.html

    ************************************************************

    Traceback (most recent call last):
      File "&lt;string&gt;", line 1, in &lt;module&gt;
      File "C:\Users\ユーザー名\AppData\Local\Temp\pip-install-dgapbvnt\cupy\setup
.py", line 65, in &lt;module&gt;
        ext_modules = cupy_setup_build.get_ext_modules()
      File "C:\Users\ユーザー名\AppData\Local\Temp\pip-install-dgapbvnt\cupy\cupy_
setup_build.py", line 561, in get_ext_modules
        extensions = make_extensions(arg_options, compiler, use_cython)
      File "C:\Users\ユーザー名\AppData\Local\Temp\pip-install-dgapbvnt\cupy\cupy_
setup_build.py", line 374, in make_extensions
        raise Exception('Your CUDA environment is invalid. '
    Exception: Your CUDA environment is invalid. Please check above error log.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ユーザー名
\AppData\Local\Temp\pip-install-dgapbvnt\cupy\
</code></pre>
<!-- {% endraw %} -->
