---
layout: post
title: "pymediainfoが利用できずエラーが発生する"
date: 2018-01-04 14:37:16
categories: python windows
---
<h1>環境説明</h1>

<p>pymediainfoはメディアファイル解析ツールであるmediainfoのpythonラッパーです。</p>

<p>Windows10環境にmediaInfoをインストール行い、pycharmを利用してpymdeiainfoのパッケージをインストールをした上で下記コードを実行しました。</p>

<p>Welcome to pymediainfo’s documentation!<br>
<a href="https://pymediainfo.readthedocs.io/en/latest/" rel="nofollow noreferrer">https://pymediainfo.readthedocs.io/en/latest/</a></p>

<h1>実行コード</h1>

<pre><code>from pymediainfo import MediaInfo
media_info = MediaInfo.parse('指定の動画ファイルパス')
for track in media_info.tracks:
    if track.track_type == 'Video':
        print track.bit_rate, track.bit_rate_mode, track.codec
</code></pre>

<h1>エラー文</h1>

<pre><code>Traceback (most recent call last):
  File "ディレクトリパス/script.py", line 110, in &lt;module&gt;
    media_info = MediaInfo.parse(filepath)
  File "C:\Python34\lib\site-packages\pymediainfo\__init__.py", line 176, in parse
    lib = cls._get_library(library_file)
  File "C:\Python34\lib\site-packages\pymediainfo\__init__.py", line 142, in _get_library
    return windll.MediaInfo
  File "C:\Python34\lib\ctypes\__init__.py", line 421, in __getattr__
    dll = self._dlltype(name)
  File "C:\Python34\lib\ctypes\__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 指定されたモジュールが見つかりません。

Process finished with exit code 1
</code></pre>

<h1>問題点</h1>

<p>下記リンクを見てみると、似たような問題の方がいます。<br>
恐らくmediainfo.dllが読み込まれていない事が原因だと思うのですが、対処方法が不明です。<br>
おわかりの方がいれば教えていただきたいです。</p>

<p><a href="https://stackoverflow.com/questions/36453900/python-pymediainfo-module-error-126-the-specified-module-could-not-be-found">https://stackoverflow.com/questions/36453900/python-pymediainfo-module-error-126-the-specified-module-could-not-be-found</a></p>
