---
layout: post
title: tensorflowのplaceholderに渡したもののshapeが違うと怒られる
date: 2019-03-08 15:00:48
categories: python tensorflow
---
<!-- {% raw %} -->
<p>MNIST手書き文字認識を2層のNNでやってみました<br>
コードはこちらになります<a href="https://gist.github.com/naoppy/d5e74476ce4d44b399c09184b5a7e46a" rel="nofollow noreferrer">gist</a><br>
12Cell目のif内でsummary_opを実行するとエラーで落ちます。<br>
エラー内容はx(name=input_x)のshapeがおかしい？ということのようですが、そんなはずはなく、悩んでいます。<br>
しかも、カーネルを再起動して動かすと一回目の実行はエラーを吐かずにうまく行きますが、2回目の実行(Run All)から必ずそこでエラーで落ちます。</p>

<p>環境ですが、tensorflow1.12.0, python3.6.8, ipython7.3.0, conda4.5.12となります。</p>

<p><a href="https://ja.stackoverflow.com/questions/51044/tensorflow%E3%81%AEplaceholder-%E3%82%A8%E3%83%A9%E3%83%BC%E3%81%8C%E8%A7%A3%E6%B1%BA%E3%81%97%E3%81%AA%E3%81%84">恐らく同様のエラーと思われる質問</a>があったのですが、解決していないようなので質問させていただきました。</p>
<!-- {% endraw %} -->
