---
layout: post
title: how results long running recognize error message?
date: 2019-11-27 07:34:25
categories: google-cloud
---
<p>I wrote below,</p>

```

my_request_body={'audio': {'uri': 'gs://sumple/test.flac'},
 'config': {'diarizationConfig': {'enable_speaker_diarization': True,
   'max_speaker_count': 5,
   'min_speaker_count': 1},
  'encoding': &lt;AudioEncoding.FLAC: 2&gt;,
  'languageCode': 'ja-JP',
  'model': 'default',
  'sampleRateHertz': 16000}}

response_g = speech_service.speech().longrunningrecognize(body=my_request_body).execute()

```

<p>And I search result by below command.</p>

```
import requests

params = (
    ('key', '-----'),
)

response_ghttp = requests.get('https://speech.googleapis.com/v1/operations/%7Bname=4846154241986901642%7D', params=params)
response_list = requests.get('https://speech.googleapis.com/v1/operations', params=params)

```

<p>but, response said</p>

```
{
  "error": {
    "code": 400,
    "message": "Unrecognized long running operation name: {name=4846154241986901642}",
    "status": "INVALID_ARGUMENT"
  }

```

<p>Please tell me why !!</p>

<p>In above, 'name' is result of type 'response_g'like that</p>

```
{'name': '4846154241986901642%7D}
```
